version: 1.7.0-{branch}{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - dev
  - ci-preparations
skip_tags: true
skip_commits:
  files:
    - Assets/*
    - .gitattributes
    - .gitignore
    - LICENSE.md
    - README.md
image: Visual Studio 2017
assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: 1.7.0.{build}
  assembly_file_version: 1.7.0.{build}
  assembly_informational_version: 1.7.0.{build}
build_script:
- ps: '& ".\Build.ps1"'
deploy:
- provider: Environment
  name: MyGet
- provider: Environment
  name: NuGet
  on:
    branch: master
- provider: Environment
  name: GitHub Releases
  on:
    branch: master
