version: 1.7.1-{branch}{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - dev
skip_tags: true
skip_commits:
  files:
    - Assets/*
    - .gitattributes
    - .gitignore
    - LICENSE.md
    - README.md
image: Visual Studio 2017
assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: 1.7.1.{build}
  assembly_file_version: 1.7.1.{build}
  assembly_informational_version: 1.7.1.{build}
build_script:
- ps: '& .\AppVeyor-Build.ps1'
deploy:
- provider: Environment
  name: MyGet
  on:
    SKIP_DEPLOYMENT: false
- provider: Environment
  name: NuGet
  on:
    branch: master
    SKIP_DEPLOYMENT: false
- provider: Environment
  name: GitHub Releases
  on:
    branch: master
    SKIP_DEPLOYMENT: false
